services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: snippet-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: snippets
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - snippet-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Express API Backend
  api:
    build: ./api
    container_name: snippet-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/snippets?authSource=admin
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - snippet-network
    command: sh -c "cd /app && npm test && npm start"

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: snippet-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3000
    ports:
      - "3030:3030"
    depends_on:
      - api
    networks:
      - snippet-network

volumes:
  mongodb_data:

networks:
  snippet-network:
    driver: bridge 