services:
  # Next.js Frontend (Development with Hot Reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: snippet-frontend-dev
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NODE_ENV: development
      PORT: 3030
      HOSTNAME: "0.0.0.0"
    ports:
      - "3030:3030"
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
      # Exclude .next build directory
      - /app/.next
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 